// A curated list of Egyptian universities (public, national, and notable private)
// Used for the Settings > Profile university dropdown
export const EGYPT_UNIVERSITIES: string[] = [
  // Public / National Universities
  "Ain Shams University",
  "Alexandria University",
  "Al-Azhar University",
  "Arish University",
  "Aswan University",
  "Assiut University",
  "Badr University in Assiut (BUA)",
  "Beni-Suef University",
  "Benha University",
  "Cairo University",
  "Damanhour University",
  "Damietta University",
  "Fayoum University",
  "Galala University",
  "Helwan University",
  "Kafrelsheikh University",
  "King Salman International University",
  "Luxor University",
  "Mansoura University",
  "Matrouh University",
  "Menoufia University",
  "Minia University",
  "Misr University for Science & Technology",
  "New Mansoura University",
  "New Valley University",
  "Port Said University",
  "Sadat City University",
  "South Valley University",
  "Suez Canal University",
  "Suez University",
  "Tanta University",
  "Zagazig University",

  // Private / International
  "The American University in Cairo (AUC)",
  "The British University in Egypt (BUE)",
  "German University in Cairo (GUC)",
  "Nile University",
  "Zewail City University of Science and Technology",
  "Modern Sciences and Arts University (MSA)",
  "Future University in Egypt (FUE)",
  "October 6 University (O6U)",
  "Pharos University in Alexandria (PUA)",
  "Delta University for Science and Technology",
  "Nahda University (NUB)",
  "Badr University in Cairo (BUC)",
  "Newgiza University (NGU)",
  "Sinai University",
  "Horus University in Egypt (HUE)",
  "Egyptian Russian University (ERU)",
  "Egyptian Chinese University (ECU)",
  "Heliopolis University",
  "Deraya University",
  "Sphinx University",
  "University of Canada in Egypt (CIC)",
  "Arab Academy for Science, Technology & Maritime Transport (AASTMT)",
].sort();

export const OTHER_UNI_VALUE = "Other";
